eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://eureka-elb-114619022.us-east-2.elb.amazonaws.com/eureka/
  instance:
    leaseExpirationDurationInSeconds: 1
    leaseRenewalIntervalInSeconds: 28
    prefer-ip-address: true
spring:
  application:
    name: student-app

