eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://eureka-server-alb-1240198838.us-east-2.elb.amazonaws.com/
  instance:
    leaseExpirationDurationInSeconds: 1
    leaseRenewalIntervalInSeconds: 28
    prefer-ip-address: true
spring:
  application:
    name: studentservice

