
spring:
  application:
   name: student-app
server:
  port: 8080
  servlet:
    context-path: /student
eureka:
  client:
    enabled: false
  registerWithEureka: false
  fetchRegistry: false
  serviceUrl:
    defaultZone: http://localhost:8761/eureka/
    

    